Qms apis update
doubtbuddy/qms-apis pull request #1
Opened 2021-12-13 03:59 UTC by muskan-2606

2021-12-28 21:32 UTC, komekez requested changes
Discuss and Complete the following changes

2021-12-28 21:32 UTC, komekez commented on src/common/db.ts
>      // let dbUrl = 'mongodb://127.0.0.1:27017/qms-dev';
Remove this commented line

2021-12-28 21:32 UTC, komekez commented on src/common/db.ts
> +// https://www.mongodb.com/blog/post/quick-start-nodejs-mongodb--how-to-get-connected-to-your-database
We dont require this kind of comments

2021-12-28 21:32 UTC, komekez commented on src/apps/uploadtoS3/router.ts
> +});
Fetch the creds from env

2021-12-28 21:32 UTC, komekez commented on src/apps/uploadtoS3/router.ts
> +};
pass the parameters

2021-12-28 21:32 UTC, komekez commented on src/apps/uploadtoS3/router.ts
> +router.post('/api/file/upload', upload.single("file"),(req: { file: { originalname: string; buffer: null; }; },res: { status: (arg0: number) => { (): any; new(): any; json: { (arg0: { error: string;
Format the code in proper order and comment about the working of the code

2021-12-28 21:33 UTC, komekez commented
Need to setup the stage for testing the code

2022-01-01 08:04 UTC, muskan-2606 commented on src/apps/uploadtoS3/router.ts
> +});
done

2022-01-01 08:04 UTC, muskan-2606 commented on src/common/db.ts
>      // let dbUrl = 'mongodb://127.0.0.1:27017/qms-dev';
done

2022-01-05 02:38 UTC, komekez approved these changes

2022-01-07 08:21 UTC, komekez approved these changes

2022-01-07 08:21 UTC, merged